### ISSUE TITLE
Image doesn't fit.

### ISSUE THREAD

**Issue by CJPrker** [SheffieldJournalism/multimedia-template#1]
Hi, one of the images we're using on our website isn't displaying properly when viewing on a desktop. When the webpage is shrunk to tablet size, the full image appears, but the responsive messes up when we load it to full screen and cuts off the top 20% or so. How do we deal with this?

**Comment by haddersbadders** [comment]
@CJPrker is it an image within the text e.g. `<img src="images/image.jpg/">` or one of the background images?

**Comment by CJPrker** [comment]
It's okay I found a work around
